"use client";

import type { SpecsListApi } from "@/lib/hooks/useSpecsList";

interface SpecsEditorProps {
  specs: SpecsListApi;
  // Suggested labels for this module (CollectionConfig.specTemplate). Rendered
  // as quick-add chips for labels not already present.
  templateSuggestions?: readonly string[];
  label?: string;
}

/**
 * Editable label/value spec rows for the Add and Edit modals (and the Detail
 * modal's edit mode). AI-sourced rows show a small badge; any edit flips the
 * row to manual via the useSpecsList hook.
 */
export default function SpecsEditor({ specs, templateSuggestions, label = "Specs" }: SpecsEditorProps) {
  const usedLabels = new Set(specs.rows.map((r) => r.label.trim().toLowerCase()).filter(Boolean));
  const suggestions = (templateSuggestions ?? []).filter((t) => !usedLabels.has(t.toLowerCase()));

  return (
    <div>
      <div className="flex items-center justify-between mb-1.5">
        <label className="block text-sm font-medium text-text-muted">{label}</label>
        <span className="text-xs text-text-dim">Structured detail for listings</span>
      </div>

      <div className="space-y-2">
        {specs.rows.map((row) => (
          <div key={row.key} className="flex items-center gap-2">
            <input
              value={row.label}
              onChange={(e) => specs.updateLabel(row.key, e.target.value)}
              placeholder="Spec"
              className="w-2/5 bg-surface-2 border border-border text-text rounded-xl px-3 py-2 text-sm focus:border-accent focus:ring-1 focus:ring-accent outline-none"
            />
            <input
              value={row.value}
              onChange={(e) => specs.updateValue(row.key, e.target.value)}
              placeholder="Value"
              className="flex-1 bg-surface-2 border border-border text-text rounded-xl px-3 py-2 text-sm focus:border-accent focus:ring-1 focus:ring-accent outline-none"
            />
            {row.source === "ai" && (
              <span
                title="Generated by AI — editing makes it a manual override"
                className="text-[10px] font-semibold uppercase tracking-wide text-sky-400 bg-sky-900/30 border border-sky-700/40 rounded-md px-1.5 py-1 select-none"
              >
                AI
              </span>
            )}
            <button
              type="button"
              onClick={() => specs.removeRow(row.key)}
              aria-label="Remove spec"
              className="shrink-0 w-8 h-8 flex items-center justify-center rounded-lg text-text-dim hover:text-red-400 hover:bg-red-900/20 transition-colors"
            >
              <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                <path strokeLinecap="round" strokeLinejoin="round" d="M6 18L18 6M6 6l12 12" />
              </svg>
            </button>
          </div>
        ))}

        {specs.rows.length === 0 && (
          <p className="text-xs text-text-dim py-1">
            No specs yet. Add rows manually, or use “Generate specs with AI” after saving.
          </p>
        )}

        <button
          type="button"
          onClick={() => specs.addRow()}
          className="text-xs font-medium text-accent hover:text-accent/80 transition-colors"
        >
          + Add spec
        </button>
      </div>

      {suggestions.length > 0 && (
        <div className="mt-3">
          <p className="text-[11px] text-text-dim mb-1.5">Quick add:</p>
          <div className="flex flex-wrap gap-1.5">
            {suggestions.map((s) => (
              <button
                key={s}
                type="button"
                onClick={() => specs.addRow(s)}
                className="text-[11px] text-text-muted border border-border bg-surface-2 rounded-full px-2.5 py-1 hover:border-accent/40 hover:text-accent transition-colors"
              >
                {s}
              </button>
            ))}
          </div>
        </div>
      )}
    </div>
  );
}
